Dataset:
    dataset_type: voc
    dataset_path: null

Training:
    batch_size: 32
    epochs: 100
    initial_learning_rate: 1e-4
    start_iter: 0
    resume: null

Evaluation:
    period: 1

Task:
    distillation: false
    target_net: mobilenet

SSDLite:
    input_size: 300
    feature_maps_size: [19, 10, 5, 3, 2, 1]
    steps: [16, 32, 64, 100, 150, 300]
    min_sizes: [60, 105, 150, 195, 240, 285]
    max_sizes: [105, 150, 195, 240, 285, 330]
    aspect_ratios: [[2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [2, 3]]
    variance: [0.1, 0.2]
    clip: true
