Dataset:
    dataset_type: voc
    dataset_path: null

Training:
    batch_size: 32
    epochs: 100
    initial_learning_rate: 1e-4
    start_iter: 0
    resume: null

Evaluation:
    period: 1

Task:
    distillation: false
    target_net: mobilenet
