name: Pylint

on: 
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint==2.10.2
    - name: Analysing the code with pylint
      run: |
        pylint --rcfile=pylint.conf --output-format=colorized odkd
